import type React from 'react';

/**
 * Shared inline styles, tracking DESIGN.md's committed palette: blue means
 * settled, yellow means waiting on you, flat surfaces separated by hairlines,
 * tabular figures on every number. Token plumbing (CSS custom properties) is
 * inlined in index.html; these read from it. No spinner styles exist here on
 * purpose — every read and write in this app touches only Dexie.
 */
export const s: Record<string, React.CSSProperties> = {
  shell: { display: 'flex', flexDirection: 'column', height: '100%' },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 24,
    padding: '12px 20px',
    background: 'var(--panel)',
    borderBottom: '1px solid var(--hairline)',
  },
  wordmark: { fontSize: 15, fontWeight: 600, letterSpacing: '-0.01em' },
  statusWell: { display: 'flex', alignItems: 'center', gap: 12, minHeight: 24 },
  settled: {
    padding: '3px 9px',
    background: 'var(--blue-wash)',
    color: 'var(--signal-blue)',
    fontSize: 12,
    fontWeight: 600,
  },
  waiting: {
    padding: '3px 9px',
    background: 'var(--yellow-wash)',
    color: 'var(--ink)',
    fontSize: 12,
    fontWeight: 600,
  },
  meta: { fontSize: 12, color: 'var(--ink-muted)' },

  nav: {
    display: 'flex',
    gap: 4,
    padding: '0 20px',
    background: 'var(--panel)',
    borderBottom: '1px solid var(--hairline)',
  },
  tab: {
    padding: '10px 14px',
    fontSize: 13,
    fontWeight: 600,
    color: 'var(--ink-muted)',
    background: 'none',
    border: 'none',
    borderBottom: '2px solid transparent',
    cursor: 'pointer',
  },
  tabActive: {
    color: 'var(--ink)',
    borderBottom: '2px solid var(--signal-blue)',
  },

  main: { padding: '28px 20px', maxWidth: 980, width: '100%', overflowY: 'auto' },
  title: { fontSize: 22, fontWeight: 600, margin: '0 0 18px', letterSpacing: '-0.02em' },
  form: { display: 'flex', gap: 8, marginBottom: 28, flexWrap: 'wrap' },
  input: {
    flex: '0 1 220px',
    padding: '9px 11px',
    fontSize: 14,
    color: 'var(--ink)',
    background: 'var(--panel)',
    border: '1px solid var(--hairline)',
    borderRadius: 3,
  },
  primary: {
    padding: '9px 18px',
    fontSize: 14,
    fontWeight: 600,
    color: '#fff',
    background: 'var(--signal-blue)',
    border: 'none',
    borderRadius: 3,
    cursor: 'pointer',
  },
  ghost: {
    padding: '7px 12px',
    fontSize: 13,
    fontWeight: 600,
    color: 'var(--ink)',
    background: 'var(--panel)',
    border: '1px solid var(--hairline)',
    borderRadius: 3,
    cursor: 'pointer',
  },
  table: { width: '100%', borderCollapse: 'collapse', background: 'var(--panel)' },
  th: {
    padding: '9px 12px',
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    color: 'var(--ink-muted)',
    textAlign: 'left',
    borderBottom: '1px solid var(--hairline)',
  },
  td: { padding: '11px 12px', fontSize: 14, borderBottom: '1px solid var(--hairline)' },
  num: { fontVariantNumeric: 'tabular-nums', textAlign: 'right' },
  empty: { padding: '28px 12px', fontSize: 14, color: 'var(--ink-muted)', textAlign: 'center' },

  columns: { display: 'flex', gap: 24, alignItems: 'flex-start', flexWrap: 'wrap' },
  panel: {
    flex: '1 1 300px',
    background: 'var(--panel)',
    border: '1px solid var(--hairline)',
    borderRadius: 4,
    padding: 16,
  },
  panelTitle: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    color: 'var(--ink-muted)',
    margin: '0 0 12px',
  },
  catalogRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 0',
    borderBottom: '1px solid var(--hairline)',
    cursor: 'pointer',
  },
  totalRow: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: 14,
    padding: '4px 0',
  },
  grandTotal: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: 18,
    fontWeight: 700,
    padding: '10px 0 4px',
    borderTop: '1px solid var(--hairline)',
    marginTop: 8,
  },
  banner: {
    padding: '9px 12px',
    background: 'var(--yellow-wash)',
    color: 'var(--ink)',
    fontSize: 13,
    fontWeight: 600,
    borderRadius: 3,
    marginBottom: 16,
  },
  label: { fontSize: 12, color: 'var(--ink-muted)', display: 'block', marginBottom: 4 },
};
